sudo: false
language: python
cache: pip
python:
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install tox-travis
script:
  - find . -maxdepth 1 -name \*.py -exec pycodestyle --ignore E501 {} +
  - tox
